### ISSUE TITLE
Make plugin to be jsonschema2pojo official plugin

### ISSUE THREAD

**Issue by AlexTrotsenko** [eirnym/js2p-gradle#4]
1. Update readme so that it's written, that it's official Gradle plugin of [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo)
_(I have created the MR for this: https://github.com/eirnym/js2p-gradle/pull/3)_
2.  Update the name of the repo and the plugin from `js2p` to `jsonschema2pojo` so that it's easier to discover and understandable by everyone.
_(As far as I know GitHub will automatically redirect from old name https://github.com/eirnym/js2p-gradle to the new one.)_
3. Reflect **"official"** status on the Gradle plugin portal and add `jsonschema2pojo` in the plugin name and:
- either  redirect if possible from old plugin page to the new plugin page
- or otherwise add the link in the old page in order to point to the new name by adding notice and the link in https://plugins.gradle.org/plugin/com.github.eirnym.js2p or , etc.
_(Feel free to check and judge what should be done there by yourself)_

**Comment by eirnym** [comment]
Hi,

I'm sorry, past year was tough for me, but I finished the task and we can go further.

Your PR is merged, name is changed
