### ISSUE TITLE
usage of deprecated pulgin

### ISSUE THREAD

**Issue by hannesa2** [eirnym/js2p-gradle#8]
https://github.com/eirnym/js2p-gradle/blob/48448299fde75215819f643b6b8be2a40cab1e98/build.gradle#L35

You use it here, but it's deprecated. Isn't it smarter to move the stuff here, or even much smarter to maintain the other one instead of this repo ? 
It's only very confusing !

**Comment by huehnerlady** [comment]
Is there an update on this? I agree I find it very confusing why the other one is deprecated 🤔

**Comment by eirnym** [comment]
Thank you for an issue, could you guide me what is deprecated? And PR is welcome :)

PS: As far as I read documentation on Gradle, `implementation` is actually suggested way to define dependencies. Am I misread it?

**Comment by hannesa2** [comment]
Sorry, a lot of time is in between ....
As far as I remember there were two repos and one was deprecated and this should be the future .... am I right ? 

If yes: why ?
What's against do harmonize them ?

**Comment by eirnym** [comment]
There's a very old gradle plugin in jsonschema2pojo and I created this one as I needed it at work. Later we [decided](https://github.com/joelittlejohn/jsonschema2pojo/issues/1070) with the author to make this one as an official plugin (this task waited almost for a year). 

Few days ago my repo was [cloned](https://github.com/niebes/js2p-gradle/tree/kotlin) and updated to have better support for Kotlin. I asked author to make a PR, and if it won't happen for some reason, I'll copy their changes.

**Comment by hannesa2** [comment]
> You use it here, but it's deprecated. Isn't it smarter to move the stuff here, or even much smarter to maintain the other one instead of this repo ?
> It's only very confusing !

Isn't it smarter to make you a maintainer in https://github.com/joelittlejohn/jsonschema2pojo and move this changes there to avoid confusion ?

If it's not possible, you need a good `README.md` like in the old deprecated. In the old, I would remove a lot content in `README.md`

Sadly, the future of a lot of Github projects: the maintainer disappears and project dies slowly.
There is no relay race culture for that.
Please add one (or more) person to the maintainer list, to avoid a dead project

**Comment by eirnym** [comment]
The issue that I can't use other plugin with grade 6.2.2 was open for a month. And original repository is maven based, not grade based. 

By the way, other projects do the same, like checkerframework.

**Comment by eirnym** [comment]
Do you want to be a maintainer?

**Comment by hannesa2** [comment]
Ok, I can do. But mostly as backup to avoid a dead project

**Comment by hannesa2** [comment]
Currently there is 
https://github.com/joelittlejohn/jsonschema2pojo
https://github.com/eirnym/js2p-gradle/

Why not create an organization `jsonschema` and move repos to it

https://github.com/jsonschema/jsonschema2pojo
https://github.com/jsonschema/js2p-gradle

... or similar. Then it's clear, that they belong to each other

**Comment by eirnym** [comment]
I proposed that way, but this was rejected

**Comment by hannesa2** [comment]
Btw, the oranization https://github.com/jsonschema is already occupied

**Comment by hannesa2** [comment]
What do you think to move this repo to https://github.com/schemajson 
I invited you and will make you an owner, when you accept the invitation

**Comment by eirnym** [comment]
Which JSON schema related repositories you want to have in this organization? If we're talking on Java, there's a lot of them covering various parts.

You already mentioned 2 of them, I'd add JsonToKotlinClass and their gradle plugin. What's about checking? what's about integration with Spring for example?

**Comment by hannesa2** [comment]
I deleted the organization, but I recommend to search for an own name.

Having this "official jsonschema2pojo Gradle plugin" in your _personal account_ does not help from the do-what-you-whant-but-leave-me-alone suspect of the well-known predecessor repo.

Having an organization comes with the touch of more professionalism and more support

**Comment by eirnym** [comment]
I'll think about this. It's not a question, where we should rush things. 

BTW, there's checkerframework with the same model
